vich_uploader:
    db_driver: orm

    mappings:
        posts:
            uri_prefix: '%post_images%'
            upload_destination: '%kernel.project_dir%/public%post_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
